# Generated by Django 5.0.6 on 2024-05-17 13:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_messages_bidservice_date_added_getstarted_date_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=250)),
                ('quotation', models.CharField(max_length=250)),
                ('expected_time', models.CharField(max_length=250)),
                ('colaboration', models.CharField(max_length=250)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
